---
- name: Determine latest GitHub release (local)
  delegate_to: localhost
  become: false
  uri:
    url: "https://api.github.com/repos/seaweedfs/seaweedfs/releases/latest"
    body_format: json
  register: _github_release
  until: _github_release.status == 200
  run_once: true
  retries: 5

- name: Set weed_version
  set_fact:
    weed_version: "{{ _github_release.json.tag_name
      | regex_replace('^v?([0-9\\.]+)$', '\\1') }}"

- name: Set node_exporter_download_url
  set_fact:
    weed_download_url: https://github.com/seaweedfs/seaweedfs/releases/download/{{ weed_version }}/linux_{{ weed_arch }}{{ '_large_disk' if weed_large_disk else ''}}.tar.gz
